[versions]
kotlin = "2.4.0"
serialization = "1.11.0"
agp = "8.12.3"
kotlinxIoCore = "0.9.0"
kotlinpoet = "2.2.0"
asp = "20260610"
sbombastic = "0.0.3"
bouncycastle = "1.85"
testballoon = "1.0.1-K2.4.0"
testballoonAddons = "0.16.0"
spotless = "8.2.1"
jmh = "1.37"
jmhPlugin = "0.7.3"

[libraries]
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIoCore" }
#for build logic conventions plugin, as it needs the artefact, not the plugin ID
asp = { module = "at.asitplus.gradle:k2", version.ref = "asp" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
sbombastic = { module = "at.asitplus.gradle.sbombastic:at.asitplus.gradle.sbombastic.gradle.plugin", version.ref = "sbombastic" }
bouncycastle-prov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
bouncycastle-pkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }

[plugins]
asp = { id = "at.asitplus.gradle.conventions", version.ref = "asp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
sbombastic = { id = "at.asitplus.gradle.sbombastic", version.ref = "sbombastic" }
jmh = { id = "me.champeau.jmh", version.ref = "jmhPlugin" }
